#ifndef SRC_CONSTANTS_
#define SRC_CONSTANTS_

#define INPUT_HEIGHT_SCALE (540)
#define INPUT_WIDTH_SCALE (960)
#define INPUT_HEIGHT_DIFF (264)
#define INPUT_WIDTH_DIFF (474)
#define SIZE_COMPRESS (264 * 474)
#define FRAME_SIZE (INPUT_WIDTH_SCALE * INPUT_HEIGHT_SCALE)
#define FRAMES (200)
#define MAX_OUTPUT_SIZE (5000 * 1024 * 10)

#endif