catch {::common::set_param -quiet hls.xocc.mode csynth};
# 
# HLS run script generated by v++ compiler
# 

open_project hardware_encoding
set_top hardware_encoding
# v++ -g, -D, -I, --advanced.prop kernel.hardware_encoding.kernel_flags
add_files "/mnt/castor/seas_home/c/chen3xn/ese532_code/project_1127/ESE5320-Final-Project/Server/lzw.cpp" -cflags " -g -I /mnt/castor/seas_home/c/chen3xn/ese532_code/project_1127/ESE5320-Final-Project/Server "
open_solution -flow_target vitis solution
set_part xczu3eg-sbva484-1-i
create_clock -period 150.000000MHz -name default
# v++ -g or --profile_kernel stall
config_rtl -kernel_profile
# v++ --advanced.param compiler.hlsDataflowStrictMode
config_dataflow -strict_mode warning
# v++ -g
config_debug -enable
# v++ --advanced.param compiler.deadlockDetection
config_export -disable_deadlock_detection=true
# v++ --advanced.param compiler.axiDeadLockFree
config_rtl -m_axi_conservative_mode=1
config_interface -m_axi_addr64
# v++ --hls.max_memory_ports
config_interface -m_axi_auto_max_ports=0
config_export -format ip_catalog -ipname hardware_encoding
csynth_design
export_design
close_project
puts "HLS completed successfully"
exit
