# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/castor/seas_home/c/chen3xn/ese532_code/project_1127/ESE5320-Final-Project/_x/link/vivado/vpl/prj/prj.srcs/sources_1/bd/u96v2_sbc_base/ip/u96v2_sbc_base_hardware_encoding_1_0/u96v2_sbc_base_hardware_encoding_1_0.xci
# IP: The module: 'u96v2_sbc_base_hardware_encoding_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/castor/seas_home/c/chen3xn/ese532_code/project_1127/ESE5320-Final-Project/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/u96v2_sbc_base/ip/u96v2_sbc_base_hardware_encoding_1_0/constraints/hardware_encoding_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'u96v2_sbc_base_hardware_encoding_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /mnt/castor/seas_home/c/chen3xn/ese532_code/project_1127/ESE5320-Final-Project/_x/link/vivado/vpl/prj/prj.srcs/sources_1/bd/u96v2_sbc_base/ip/u96v2_sbc_base_hardware_encoding_1_0/u96v2_sbc_base_hardware_encoding_1_0.xci
# IP: The module: 'u96v2_sbc_base_hardware_encoding_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/castor/seas_home/c/chen3xn/ese532_code/project_1127/ESE5320-Final-Project/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/u96v2_sbc_base/ip/u96v2_sbc_base_hardware_encoding_1_0/constraints/hardware_encoding_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'u96v2_sbc_base_hardware_encoding_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
